version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_training
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: training_db
      MYSQL_USER: training_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL/test.sql:/docker-entrypoint-initdb.d/test.sql

volumes:
  db_data: